### ISSUE TITLE
Codec issue

### ISSUE THREAD

**Issue by xIneffable** [kovinevmv/getcontact#10]
Time to time it outputs me error smth like that
'charmap' codec can't encode characters in position 6-8: character maps to <undefined>

I think it is connected with russian or ukrainian language and codec cannot recognize this words. Can you help to solve this problem?

**Comment by kovinevmv** [comment]
If you provide an example of an incoming number, then I will try to debug it

**Comment by xIneffable** [comment]
python main.py -p +380501637577
Phone: +380501637577
User: Yurii Pavlenko
Tag list:
         Юра Павленко
         Юра Лос-анджелес
         Traceback (most recent call last):
  File "main.py", line 19, in <module>
    getcontact.print_information_by_phone(phone)
  File "C:\Users\Iam\Desktop\Programming\Python\getcontact\src\getcontact\getcontact.py", line 80, in print_information_by_phone
    self._print_beauty_output(data)
  File "C:\Users\Iam\Desktop\Programming\Python\OSINT\Phone\getcontact\src\getcontact\getcontact.py", line 93, in _print_beauty_output
    print("\t", tag)
  File "C:\Users\Iam\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2764' in position 6: character maps to <undefined>

**Comment by xIneffable** [comment]
At the begining it works but then programme interrupts and get error

**Comment by kovinevmv** [comment]
Check update.
The error occurs because there is no emoji on your system. It can't decode it

**Comment by xIneffable** [comment]
I updated your repo but the problem the same

**Comment by xIneffable** [comment]
Phone: +380501637577
User: Yurii Pavlenko
Tag list:
         Юра Павленко
         Юра Лос-анджелес
         Traceback (most recent call last):
  File "main.py", line 19, in <module>
    getcontact.print_information_by_phone(phone)
  File "C:\Users\ian\Desktop\Programming\Python\getcontact\src\getcontact\getcontact.py", line 80, in print_information_by_phone
    self._print_beauty_output(data)
  File "C:\Users\ian\Desktop\Programming\Python\OSINT\Phone\getcontact\src\getcontact\getcontact.py", line 93, in _print_beauty_output
    print("\t", tag.encode('utf-8', errors='replace').decode('utf-8', errors='replace'))
  File "C:\Users\ian\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2764' in position 6: character maps to <undefined>

**Comment by kovinevmv** [comment]
What is your operation system or you are using docker?

**Comment by xIneffable** [comment]
My operation system is Windows 8.1 and i'm using python

**Comment by xIneffable** [comment]
is it possible to make smth?

**Comment by kovinevmv** [comment]
Try to run docker. Do you use IDE? Maybe [this](https://stackoverflow.com/questions/30955589/python-3-4-encoding-in-windows-8-1) can help you. 

Script can't print in terminal emoji. Most likely, the terminal does not support such characters. Change the encoding in the terminal

**Comment by xIneffable** [comment]
Thank you but I solved it by running windows terminal. In general it was problem with my downloaded, from internet, terminal.
