### ISSUE TITLE
Error when running docker

### ISSUE THREAD

**Issue by edmonAvetisyan555** [kovinevmv/getcontact#32]
**Describe the bug**

**To Reproduce**
1. Tryng to run  `sudo docker run -t getcontact -p +792910453XX`

**Desktop (please complete the following information):**
 - Docker [true]

**Log**
```bash
sudo docker run -t getcontact -p +792910453XX
/usr/local/lib/python3.8/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Captcha is detected. 
Traceback (most recent call last):
  File "./src/main.py", line 26, in <module>
    getcontact.print_information_by_phone(phone)
  File "/src/getcontact/getcontact.py", line 94, in print_information_by_phone
    data = self.get_information_by_phone(phone)
  File "/src/getcontact/getcontact.py", line 85, in get_information_by_phone
    result_name = self.get_name_by_phone(phone)
  File "/src/getcontact/getcontact.py", line 19, in get_name_by_phone
    response = self.requester.get_phone_name(phoneNumber)
  File "/src/getcontact/requester.py", line 146, in get_phone_name
    return self.send_req_to_the_server(
  File "/src/getcontact/requester.py", line 121, in send_req_to_the_server
    is_ok, response = self.send_request_encrypted(url, payload)
  File "/src/getcontact/requester.py", line 66, in send_request_encrypted
    return self._send_post(
  File "/src/getcontact/requester.py", line 62, in _send_post
    return self._parse_response(response)
  File "/src/getcontact/requester.py", line 95, in _parse_response
    from getcontact.decode_captcha import CaptchaDecode
  File "/src/getcontact/decode_captcha.py", line 6, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

```

**Comment by MrNagaron** [comment]
You don't have a numpy module, type in the console: sudo pip3 install numpy

**Comment by edmonAvetisyan555** [comment]
@MrNagaron  should docker install take care of all modules ?

**Comment by kovinevmv** [comment]
Update docker: https://github.com/kovinevmv/getcontact/commit/9d0cbdb137e2bbe5823b674d77a880ffbbef516b
