### ISSUE TITLE
Helpp

### ISSUE THREAD

**Issue by BonnY0** [kovinevmv/getcontact#47]
Kali linux

1, 'Error opening data file /usr/local/share/tessdata/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory. Failed loading language \'eng\' Tesseract couldn\'t load any languages! Could not initialize tesseract.')
^CTraceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./src/main.py", line 29, in <module>
    getcontact.print_information_by_phone(phone)
  File "/root/getcontact/src/getcontact/getcontact.py", line 93, in print_information_by_phone
    data = self.get_information_by_phone(phone)
  File "/root/getcontact/src/getcontact/getcontact.py", line 84, in get_information_by_phone
    result_name = self.get_name_by_phone(phone)
  File "/root/getcontact/src/getcontact/getcontact.py", line 18, in get_name_by_phone
    response = self.requester.get_phone_name(phoneNumber)
  File "/root/getcontact/src/getcontact/requester.py", line 152, in get_phone_name
    return self.send_req_to_the_server(
  File "/root/getcontact/src/getcontact/requester.py", line 122, in send_req_to_the_server
    is_ok, response = self.send_request_encrypted(url, payload)
  File "/root/getcontact/src/getcontact/requester.py", line 66, in send_request_encrypted
    return self._send_post(
  File "/root/getcontact/src/getcontact/requester.py", line 62, in _send_post
    return self._parse_response(response)
  File "/root/getcontact/src/getcontact/requester.py", line 99, in _parse_response
    self.decode_captcha(code)
  File "/root/getcontact/src/getcontact/requester.py", line 172, in decode_captcha
    return self.send_req_to_the_server(
  File "/root/getcontact/src/getcontact/requester.py", line 122, in send_req_to_the_server
    is_ok, response = self.send_request_encrypted(url, payload)
  File "/root/getcontact/src/getcontact/requester.py", line 66, in send_request_encrypted
    return self._send_post(
  File "/root/getcontact/src/getcontact/requester.py", line 62, in _send_post
    return self._parse_response(response)
  File "/root/getcontact/src/getcontact/requester.py", line 99, in _parse_response
    self.decode_captcha(code)
  File "/root/getcontact/src/getcontact/requester.py", line 172, in decode_captcha
    return self.send_req_to_the_server(
  File "/root/getcontact/src/getcontact/requester.py", line 122, in send_req_to_the_server
    is_ok, response = self.send_request_encrypted(url, payload)
  File "/root/getcontact/src/getcontact/requester.py", line 66, in send_request_encrypted
    return self._send_post(
  File "/root/getcontact/src/getcontact/requester.py", line 62, in _send_post
    return self._parse_response(response)
  File "/root/getcontact/src/getcontact/requester.py", line 99, in _parse_response
    self.decode_captcha(code)
  File "/root/getcontact/src/getcontact/requester.py", line 172, in decode_captcha
    return self.send_req_to_the_server(
  File "/root/getcontact/src/getcontact/requester.py", line 122, in send_req_to_the_server
    is_ok, response = self.send_request_encrypted(url, payload)
  File "/root/getcontact/src/getcontact/requester.py", line 66, in send_request_encrypted
    return self._send_post(
  File "/root/getcontact/src/getcontact/requester.py", line 62, in _send_post
    return self._parse_response(response)
  File "/root/getcontact/src/getcontact/requester.py", line 99, in _parse_response
    self.decode_captcha(code)
  File "/root/getcontact/src/getcontact/requester.py", line 172, in decode_captcha
    return self.send_req_to_the_server(
  File "/root/getcontact/src/getcontact/requester.py", line 122, in send_req_to_the_server
    is_ok, response = self.send_request_encrypted(url, payload)
  File "/root/getcontact/src/getcontact/requester.py", line 66, in send_request_encrypted
    return self._send_post(
  File "/root/getcontact/src/getcontact/requester.py", line 60, in _send_post
    response = requests.post(url, data=data, headers=self.headers)
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)

**Comment by kovinevmv** [comment]
Try using docker container.  I developed this script for Ubuntu 20.04. Some packages for tesseract probably missing on ur Kali
